### ISSUE TITLE
Unable to fetch chart pushed after helm package

### ISSUE THREAD

**Issue by burdiyan** [nouney/helm-gcs#2]
How to reproduce:

0. Install the plugin, init the repo and add it to your local Helm installation. 
1. `helm create foo`.
2. `helm package foo` (this will create foo-0.1.0.tgz file).
3. `helm gcs push foo-0.1.0.tgz <your-repo>`.
4. `helm repo update`.
5. `helm fetch <your-repo>/foo`.

After that I get the following error:

```
2017/11/02 22:24:13 storage: object doesn't exist
panic: storage: object doesn't exist

goroutine 1 [running]:
log.Panic(0xc42016fcf8, 0x1, 0x1)
	/usr/lib/go/src/log/log.go:330 +0xc0
github.com/nouney/helm-gcs/helm-gcs/cmd.glob..func2(0x192f220, 0xc420045760, 0x1, 0x1, 0x0, 0x0)
	/home/nouney/work/go/src/github.com/nouney/helm-gcs/helm-gcs/cmd/pull.go:19 +0xae
github.com/nouney/helm-gcs/helm-gcs/vendor/github.com/spf13/cobra.(*Command).execute(0x192f220, 0xc420045730, 0x1, 0x1, 0x192f220, 0xc420045730)
	/home/nouney/work/go/src/github.com/nouney/helm-gcs/helm-gcs/vendor/github.com/spf13/cobra/command.go:698 +0x47a
github.com/nouney/helm-gcs/helm-gcs/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x192f880, 0xc42016ff30, 0xc42016ff38, 0x14ac23e)
	/home/nouney/work/go/src/github.com/nouney/helm-gcs/helm-gcs/vendor/github.com/spf13/cobra/command.go:783 +0x30e
github.com/nouney/helm-gcs/helm-gcs/vendor/github.com/spf13/cobra.(*Command).Execute(0x192f880, 0x0, 0x192faa0)
	/home/nouney/work/go/src/github.com/nouney/helm-gcs/helm-gcs/vendor/github.com/spf13/cobra/command.go:736 +0x2b
github.com/nouney/helm-gcs/helm-gcs/cmd.Execute()
	/home/nouney/work/go/src/github.com/nouney/helm-gcs/helm-gcs/cmd/root.go:17 +0x31
main.main()
	/home/nouney/work/go/src/github.com/nouney/helm-gcs/helm-gcs/main.go:6 +0x20
```

Expected behavoir: chart foo-0.1.0.tgz being fetched.

**Comment by nouney** [comment]
I'm able to reproduce this issue only if I manually delete the file from Google Cloud Storage. Can you check if the file is in your bucket ?

**Comment by burdiyan** [comment]
@nouney For some reason this started to work after doing all the steps from the beginning. Super strange. (BTW the file was in the bucket actually, when it was not working).

I'll close this, and reopen if it will happen again.

Thanks a lot!

**Comment by sebglon** [comment]
I have the same error.

**Comment by nouney** [comment]
@sebglon 

What's the output of  `helm gcs version` please?

**Comment by sebglon** [comment]
```
version: 0.1.3
commit: dfc9a319f70f3a1e8bf895d9d685423734bb4a55
date: 2018-03-01T01:11:21Z
```

but when i show index, i have an error:
```
  http-redirect:
  - apiVersion: v1
    created: 2018-03-08T10:43:39.434579258+01:00
    description: 'Helm chart for the Akeneo: add HTTP redirect on GCE Ingress.'
    digest: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
    name: http-redirect
    urls:
    - gs://akeneo-charts/http-redirect
    version: 0.1.0
```
